version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 5s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:1.85.4
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5678:5678"
    environment:
      # Database
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n

      # UI / Auth (opcional, recomendado)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin

      # Custom nodes path (aponto para onde vou montar)
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/nodes

      # Persistência (opcional: dados do n8n no host)
      - N8N_USER_FOLDER=/home/node/.n8n

    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_custom/nodes:/home/node/.n8n/nodes:ro

volumes:
  postgres_data:
  n8n_data:
